#!/bin/bash

new=/tmp/users_new.$$
old=/tmp/users_old.$$

>$old

while true
    do
        who > $new
        diff $old $new
        mv $new $old
        echo "Anzahl Benutzer: `who | wc -l`"

        sleep 60
    done | awk '/>/ { $1 = "in: "; print }
    /</ { $1 = "out: "; print } '
